In [7]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [26]:
poisson = torch.distributions.Poisson(rate=4)

In [28]:
x = poisson.sample((3, 10, 10))

In [29]:
x[0]

tensor([[ 3.,  2.,  3.,  5.,  4.,  3.,  5.,  3.,  6.,  7.],
        [ 3.,  1.,  3.,  5.,  2.,  3.,  4.,  7.,  2.,  2.],
        [ 5.,  4.,  6.,  2.,  4.,  4.,  2.,  3.,  6.,  6.],
        [ 1.,  6., 13.,  6.,  7.,  3.,  7.,  2.,  7.,  7.],
        [ 2.,  5.,  0.,  6.,  4.,  4.,  4.,  4.,  1.,  2.],
        [ 4.,  7.,  3.,  1.,  7.,  4.,  5.,  6.,  3.,  2.],
        [ 4.,  2.,  3.,  5.,  4.,  1.,  1.,  3.,  4.,  6.],
        [ 2.,  6.,  5.,  4.,  2.,  2.,  6.,  4.,  5.,  7.],
        [ 1.,  2.,  1.,  6.,  6.,  7.,  8.,  5.,  4.,  2.],
        [ 4.,  6.,  1.,  4.,  8.,  1.,  2.,  5.,  6.,  2.]])

In [30]:
y = x.clone()

In [31]:
x[0].mean()

tensor(4.0500)

In [32]:
x[0].var()

tensor(4.6944)

In [33]:
layer = nn.BatchNorm1d(10)

In [34]:
z = layer(x)

In [40]:
z[:, :, :].var()

tensor(1.0033, grad_fn=<VarBackward0>)

In [43]:
indices = torch.tensor([2,0])
lengths_new = torch.tensor([1,2])
lengths_old = torch.tensor([2,2,3])
tensor_new = torch.tensor([[3,1,2,4], [2,1,3,4]])
tensor_old = torch.tensor([[1,2,3,4], [1,2,3,4], [2,1,3,4]])
mask = lengths_new < lengths_old[indices]
print("old value", tensor_old[indices][mask])
print("new value", tensor_new[mask])
tensor_old[indices[mask]] = tensor_new[mask]
print("result value", tensor_old[indices][mask])
print("old value", lengths_old[indices][mask])
print("new value", lengths_new[mask])
lengths_old[indices[mask]] = lengths_new[mask]
print("result value", lengths_old[indices][mask])

tensor([3, 2])
tensor([ True, False])
old value tensor([[2, 1, 3, 4]])
new value tensor([[3, 1, 2, 4]])
result value tensor([[3, 1, 2, 4]])
old value tensor([3])
new value tensor([1])
result value tensor([1])


In [45]:
x = torch.arange(12).reshape(3, 4)

In [53]:
indices = torch.tensor([[1, 2], [0, 3], [2, 1]])

In [54]:
x[indices]

IndexError: index 3 is out of bounds for dimension 0 with size 3